### ISSUE TITLE
Minor UI issues/freshening

### ISSUE THREAD

**Issue by scottcain** [virusseq/portal-ui#432]
There are a few items that should be updated on the main page:
* The link to Cancogen should be removed
* Duotang <strike>is</strike> was misspelled in the banner; the spelling should either be fixed (it has been), or if desired, the banner could be removed (it is quite old at this point)

Are there other main page/UI "minor" things that should be addressed?

**Comment by mcourtot** [comment]
Update for clarification, after email discussion with Fiona: we do not remove the logo, only the link to Cancogen (when and if the Cancogen page 'breaks')

**Comment by mcourtot** [comment]
action item: remove the hyperlink from the Cancogen logo and close this ticket when done

**Comment by justincorrigible** [comment]
Thanks for clarifying! will get those done.

**Comment by justincorrigible** [comment]
Changes applied. Closing as completed
