### ISSUE TITLE
Update Author List - BC

### ISSUE THREAD

**Issue by GH-Emily** [virusseq/portal-ui#437]
Hi @edsu7 

I'm wondering if you could please update the [author's list for BCCDC](https://virusseq-dataportal.ca/acknowledgements) to read:

Prystajecky Natalie, Linda Hoang, John R. Tyson, **James Zlosnik,** Dan Fornika, Shannon Russell, Kim MacDonald, Kimia Kamelian, Ana Pacagnella, Corrinne Ng, Loretta Janz, Richard Harrigan, Robert Azana, Tara Newman, Jessica Caleta, Sherrie Wang, Janet Fung, Mel Krajden

The name in bold is the addition. 

Thank you! 
Emily

**Comment by scottcain** [comment]
Hi @GH-Emily , This is more of a @justincorrigible thing, I'll assign it to him and he can reassign to somebody else if he wants to.

**Comment by justincorrigible** [comment]
Change made and deployed. Closing as completed
