### ISSUE TITLE
virusseq.ca links not working

### ISSUE THREAD

**Issue by eringill** [virusseq/portal-ui#438]
@scottcain, links to https://virusseq.ca from the data portal aren't working because this site doesn't exist anymore. Please redirect all of these links to https://genomecanada.ca/challenge-areas/cancogen/virusseq/

Thanks!

**Comment by scottcain** [comment]
@justincorrigible could you please grep through the codebase for any instances of virusseq.ca and change any that you find to the the link @eringill provides above? Thanks.

**Comment by justincorrigible** [comment]
Hey, and thanks for your patience with my getting back to you on this. Could've sworn I responded ages ago.
Anyway, meant to say I couldn't find any links to virusseq.ca in the codebase.

Think it's safe to close this ticket...
