### ISSUE TITLE
NS - Update to Isolate Value

### ISSUE THREAD

**Issue by KirstenPalmier** [virusseq/portal-ui#439]
Hi @edsu7 ,

Can you please update the following sample:
 | Specimen Collector Sample ID| Old isolate value | New isolate value|
|-|-|-|
|NS_17890|hCoV-19/Canada/NS-NML-17890/2021|hCoV-19/Canada/NS-NML-17890/2020|

Thank you!

Kirsten Palmier

**Comment by edsu7** [comment]
Hi @KirstenPalmier 

`NS_17890`'s `isolate` and `fasta header name` have been updated.

Please see below
Before:
![image](https://github.com/virusseq/portal-ui/assets/22638361/3b9b758b-18d9-49f5-a205-bc3cf4521fcd)
After:
![image](https://github.com/virusseq/portal-ui/assets/22638361/53123256-0c2b-45b6-88ef-44c3b6348b38)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you!
