### ISSUE TITLE
SK Raw Sequence Data Processing Method

### ISSUE THREAD

**Issue by JeffTuff** [virusseq/portal-ui#440]
Hello @edsu7,

Please update the `Raw Sequence Data Processing Method` as shown for the samples in the attached file.

Thank you!

Jeff

[SK_raw_seq_method_update_Issue778.csv](https://github.com/user-attachments/files/16089436/SK_raw_seq_method_update_Issue778.csv)

**Comment by edsu7** [comment]
Hi @JeffTuff ,

`207` samples listed in [SK_raw_seq_method_update_Issue778.csv](https://github.com/user-attachments/files/16089436/SK_raw_seq_method_update_Issue778.csv) have had their `Raw Sequence Data Processing Method`.

Please see below screenshot reflecting change:
![image](https://github.com/virusseq/portal-ui/assets/22638361/1c24127a-684d-4b6c-9832-20dfc90914f5)

Cheers,
Edmund

**Comment by justincorrigible** [comment]
Closing as completed
