### ISSUE TITLE
Data Redaction

### ISSUE THREAD

**Issue by molpratt** [virusseq/portal-ui#441]
Hi @edsu7 

Can you please remove `ON_99856` (original submission date = 2021-08-25) from the Data Portal? We will be replacing this record with updated metadata, as requested by the province, in the next submission and the new version will have a different Sample ID so I want to make sure we avoid duplication. 

Thank you!

Molly

**Comment by edsu7** [comment]
Hi @molpratt ,

Sample `ON_99856` has been redacted. Please see below:

Before:
![image](https://github.com/user-attachments/assets/253a7a26-3b3e-49e1-91cd-e8272e006c37)
After:
![image](https://github.com/user-attachments/assets/dfc47cb1-cd5b-47ea-8fa7-4cd7dcc9bcd9)

Cheers,
Edmund

**Comment by molpratt** [comment]
Thank you!
