### ISSUE TITLE
QC - Update to Purpose of Sequencing Values

### ISSUE THREAD

**Issue by molpratt** [virusseq/portal-ui#445]
Hi @edsu7 

Could you please update the Purpose of Sequencing to Baseline surveillance for the following 16 samples from QC?

specimen collector sample ID | Purpose of Sequencing (old) | Purpose of Sequencing (new)
-- | -- | --
QC_731201 | Missing | Baseline surveillance   (random sampling)
QC_731206 | Missing | Baseline surveillance   (random sampling)
QC_731282 | Missing | Baseline surveillance   (random sampling)
QC_731191 | Missing | Baseline surveillance   (random sampling)
QC_731286 | Missing | Baseline surveillance   (random sampling)
QC_731207 | Missing | Baseline surveillance   (random sampling)
QC_731280 | Missing | Baseline surveillance   (random sampling)
QC_731281 | Missing | Baseline surveillance   (random sampling)
QC_731285 | Missing | Baseline surveillance   (random sampling)
QC_731283 | Missing | Baseline surveillance   (random sampling)
QC_731203 | Missing | Baseline surveillance   (random sampling)
QC_731204 | Missing | Baseline surveillance   (random sampling)
QC_731205 | Missing | Baseline surveillance   (random sampling)
QC_731202 | Missing | Baseline surveillance   (random sampling)
QC_731284 | Missing | Baseline surveillance   (random sampling)
QC_731159 | Missing | Baseline surveillance   (random sampling)

</body>

</html>

Thank you, 

Molly

**Comment by edsu7** [comment]
Hi @molpratt,

The above twelve samples have had their `purpose_of_sequencing` updated.

Please see below:

Before:
![image](https://github.com/user-attachments/assets/186dc76c-b72e-4ebe-a5df-db77b7d107b8)

After:
![image](https://github.com/user-attachments/assets/9e6d47e9-4f30-4844-aa33-f5040f8e8644)

Cheers,
Edmund

**Comment by molpratt** [comment]
Thank you!
