### ISSUE TITLE
NL - update to raw sequence data processing method and bioinformatics protocol

### ISSUE THREAD

**Issue by KirstenPalmier** [virusseq/portal-ui#447]
Good morning @edsu7 ,

Can you please update the following samples (attached as a csv) for both the raw sequencing data processing method and bioinformatics protocol fields?

Thank you!

Please do not hesitate to reach out if you have any questions.[NL_DP_update_raw_seq_bfx_Issue839.csv](https://github.com/user-attachments/files/18011776/NL_DP_update_raw_seq_bfx_Issue839.csv)

**Comment by edsu7** [comment]
Hi @KirstenPalmier,

The 1395 samples have had their `Bioinformatics Protocol` and `Raw Sequence Data Processing Method` updated.

Please see below for example:
![Image](https://github.com/user-attachments/assets/42a9162f-4606-4fb6-851c-e018906a1e28)

Cheers,
Edmund

**Comment by KirstenPalmier** [comment]
Thank you!
